name: OrangeHRM Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener codigo fuente
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Construir proyecto con Maven
        run: mvn clean install -DskipTests

      - name: Ejecutar pruebas UI
        env:
          HEADLESS: true
        run: mvn test

      - name: Guardar reporte
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Reporte-TestNG
          path: |
            reports/
            target/surefire-reports/

 